# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Vue
                                 A QGIS plugin
 gestion des vues
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2024-11-20
        git sha              : $Format:%H$
        copyright            : (C) 2024 by Gérôme PECHEUR
        email                : gerome.pecheur@ign.fr
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from PyQt5.QtCore import Qt, QTimer
from PyQt5.QtGui import QFontMetrics
from PyQt5.QtWidgets import QPushButton, QMessageBox, QHBoxLayout, QWidget, QFrame, QScrollArea, QSizePolicy
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QInputDialog
from qgis._core import QgsMapLayer
from qgis.core import QgsProject

from .rightclic import ClicDroit
from copy import copy
import xml.etree.ElementTree as ET
import os
import shutil

HAUTEUR_BTN = 18

PATH_REP = os.path.join(os.path.dirname(__file__),"ONGLET")
PATH_REP_SYMBOLOGIE = os.path.join(PATH_REP,"symbologie")
PATH_REP_VUES = os.path.join(PATH_REP,"xml")
PATH_VUES = os.path.join(PATH_REP_VUES,"vues.xml")
VUE_DEFAUT = "courant"

# une ou plusieurs valeurs parmi : mCoordsEdit, mScaleWidget, mMagnifierWidget, mRotationLabel, mRotationEdit,
# mRenderSuppressionCBox, mOntheFlyProjectionStatusButton, mMessageLogViewerButton
LIST_VUES_QGIS_A_GARDER = ["mOntheFlyProjectionStatusButton","mScaleWidget"]


# Initialize Qt resources from file resources.py
# from .resources import *
# Import the code for the dialog
# from .vue_dialog import VueDialog

class Vue:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):

        self.filter_clic_droit = ClicDroit(self)

        self.iface = iface
        self.layer = self.iface.activeLayer()

        self.status_bar = self.iface.mainWindow().statusBar()
        self.status_bar.setContentsMargins(0, 0, 0, 0)
        self.status_bar.setFixedHeight(35)

        self.list_bouton_defaut = []
        self.btn_modifie = None
        self.btn_gauche = None
        self.btn_droit = None
        self.btn_moins = None
        self.btn_plus = None

        self.first_start = True

        self.pos_dernier_onglet = None
        self.list_onglet = []

        # --- ScrollArea horizontal ---
        self.scroll = QScrollArea()
        self.scroll.setFixedHeight(30)  # hauteur visible dans la status bar
        self.scroll.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.scroll.setHorizontalScrollBarPolicy(Qt.ScrollBarAsNeeded)
        # self.scroll.setMaximumWidth(800)
        self.scroll.setWidgetResizable(True)
        self.scroll.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Fixed)
        self.scroll.setStyleSheet("""
            QScrollArea {
                border: none;             /* supprime le contour autour du scrollarea */
                background: transparent;  /* rend le fond transparent */
            }
            QScrollBar:horizontal {
                background: #f0f0f0;         /* fond de la scrollbar */
                height: 8px
            }
            QScrollBar::handle:horizontal {
                background: #777777;             /* couleur de la barre */
            }
        """)

        # Widget interne qui contient le layout des boutons vues
        self.container_vues = QWidget()
        self.container_vues.setSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        self.container_vues.setObjectName("container_vues")
        # self.container_vues.setStyleSheet("border: 1px solid red")
        # self.container.setAttribute(Qt.WA_StyledBackground, True)

        # Widget interne qui contient le layout des boutons par defaut (+ , - ,....)
        self.container_defaut = QWidget()
        self.container_defaut.setSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        # self.container_defaut.setStyleSheet("border: 1px solid blue")
        self.container_defaut.setObjectName("container_defaut")
        # self.container.setAttribute(Qt.WA_StyledBackground, True)

        # --- Layout horizontal (qui contient les boutons des vues) ---
        self.hlayout_vues = QHBoxLayout(self.container_vues)
        self.hlayout_vues.setContentsMargins(0, 3, 0, 0)
        self.hlayout_vues.setSpacing(0)

        # --- Layout horizontal (qui contient les boutons par defaut) ---
        self.hlayout_defaut = QHBoxLayout(self.container_defaut)
        self.hlayout_defaut.setContentsMargins(0, 0, 0, 0)
        self.hlayout_defaut.setSpacing(1)

        # --- Définir le widget interne du ScrollArea ---
        self.scroll.setWidget(self.container_vues)

        self.line = QFrame()
        self.line.setFrameShape(QFrame.VLine)
        self.line.setLineWidth(2)

        self.onglet_actif = None
        self.listbtn = []

        self.list_widgets_qgis = self.getwidgetsQGIS()

        # bouton par defaut
        self.icon_plus = QIcon(os.path.join(os.path.dirname(__file__) , "icons","plus.png"))
        self.icon_moins = QIcon(os.path.join(os.path.dirname(__file__) , "icons","moins.png"))
        self.icon_fleche_droite = QIcon(os.path.join(os.path.dirname(__file__) , "icons","fleche_droite.png"))
        self.icon_fleche_gauche = QIcon(os.path.join(os.path.dirname(__file__) , "icons","fleche_gauche.png"))
        self.icon_modfie = QIcon(os.path.join(os.path.dirname(__file__) , "icons","modifie.png"))

        self.list_nom_btn_defaut = self.init_bouton_defaut()

        # aucun projet chargé
        if not QgsProject.instance().fileName():
            return


    def run_at_startup(self):
        QTimer.singleShot(500, self.run)

    def clic_droit(self,obj):
        dialinput = QInputDialog()
        new_name, ok = dialinput.getText(None, "Modifier le nom", "Nouveau nom :",text = f"{obj.objectName()}")
        if not ok:
            return
        if new_name == "":
            QMessageBox.warning(None,"Erreur","Le nom ne doit pas être vide")
            return
        if "*" in new_name:
            QMessageBox.warning(None, "Erreur", "Le nom ne doit pas être contenir '*'")
            return

        # 1: renommer l'onglet dans le xml
        tree = ET.parse(PATH_VUES)
        root = tree.getroot()
        for vue in root.findall("vue"):
            if vue.get("id") == obj.objectName():
                vue.set("id", new_name)  # modifier l'attribut 'id'
        tree.write(PATH_VUES, encoding="utf-8", xml_declaration=True)

        # 2: renommer le dossier correspondant
        os.rename(os.path.join(PATH_REP_SYMBOLOGIE,obj.objectName()),os.path.join(PATH_REP_SYMBOLOGIE, new_name))

        self.suppr_onglet_perso_from_statusbar()
        self.list_onglet = self.get_onglet_from_XML()
        self.add_onglet_from_xml()
        self.InitAspectOnglet()

        self.update_scroll_width()

        # 3 : remettre l'onglet actif
        for bouton in self.listbtn:
            if new_name == bouton.objectName():
                bouton.setStyleSheet("background-color: #2ab51a ; font-weight: bold")
        # 4 : initialiser l'onglet actif
        # self.onglet_actif = obj.objectName()

    def initGui(self):
        QgsProject.instance().readProject.connect(self.run_at_startup)

    def unload(self):
        self.clear_statusbar_plugin_widgets()

    def clear_statusbar_plugin_widgets(self):
        # Supprime container_defaut
        try:
            self.status_bar.removeWidget(self.container_defaut)
        except Exception:
            pass
        # Supprime scroll
        try:
            self.status_bar.removeWidget(self.scroll)
        except Exception:
            pass
        # Supprime éventuellement la ligne de séparation
        try:
            self.status_bar.removeWidget(self.line)
        except Exception:
            pass

    def changestyle(self,bouton):
        # sauvegarde de l'onglet actif pour gerer la suppression
        self.onglet_actif = bouton.objectName()
        list_layer = self.getlayer_par_onglet_from_XML(bouton.objectName())

        self.InitAspectOnglet()
        # bouton en vert
        bouton.setStyleSheet("background-color: #2ab51a ; font-weight: bold")

        self.masquerlayer(["ALL"])
        self.afficherlayer(list_layer)

        for layer in list_layer:
            layer_tmp = self.getlayer(layer)
            try:
                path_qml = os.path.join(PATH_REP,"symbologie",bouton.objectName(),f"{layer}.qml")
                layer_tmp.loadNamedStyle(path_qml,categories=QgsMapLayer.StyleCategory.Symbology| QgsMapLayer.Labeling)

                layer_tmp.triggerRepaint()
            # pas de style pour le layer specifié (ou repertoire manquant)
            except AttributeError:
                pass

    # retourne la liste des layers affichés par onglets specifiques
    def getlayer_par_onglet_from_XML(self,onglet):
        # Charger le fichier XML
        list_layer = []
        tree = ET.parse(PATH_VUES)
        root = tree.getroot()
        for vue in root.findall("vue"):
            vue_id = vue.get('id')
            if vue_id == onglet:
                for layer in vue.findall("layer"):
                    list_layer.append(layer.text)
                break
        return list_layer

    # retourne la liste des onglets inserés
    def get_onglet_from_XML(self):
        tree = ET.parse(PATH_VUES)
        root = tree.getroot()
        list_onglet = []
        for vue in root.findall("vue"):
            list_onglet.append(vue.get('id'))
        return list_onglet


    # masque les layer en fonction de l'onglet
    def masquerlayer(self,listlayer):
        list_tmp = []
        if listlayer[0] == "ALL":
            layers = QgsProject.instance().mapLayers()
            for layer_id, layername in layers.items():
                list_tmp.append(layername.name())
            listlayer = copy(list_tmp)

        for layer in listlayer:
            layer_tmp = self.getlayer(layer)
            QgsProject.instance().layerTreeRoot().findLayer(layer_tmp.id()).setItemVisibilityChecked(False)

    # rend visible les layer (listlayer)
    def afficherlayer(self,listlayer):
        list_tmp = []
        if len(listlayer) ==0:
            return
        if listlayer[0] == "ALL":
            layers = QgsProject.instance().mapLayers()
            for layer_id,layername in layers.items():
                list_tmp.append(layername.name())
            listlayer = copy(list_tmp)

        for layer in listlayer:
            layer_tmp = self.getlayer(layer)
            if layer_tmp:
                QgsProject.instance().layerTreeRoot().findLayer(layer_tmp.id()).setItemVisibilityChecked(True)

    # ajout OU modifie un onglet
    def ajout_onglet(self):
        # TODO ajout_onglet
        onglet,ok = QInputDialog.getText(None, 'Gestion des vues', 'Veuillez donner un nom à l\'onglet:')
        if ok:
            self.add_onglet_in_xml(onglet)
            # permet de rafraichir la barre d'etat
            # self.recharge_onglet = False
            self.suppr_onglet_perso_from_statusbar()
            self.list_onglet = self.get_onglet_from_XML()
            self.add_onglet_from_xml()
            self.addwidgetQGIS(self.list_widgets_qgis, LIST_VUES_QGIS_A_GARDER)

            # mettre le style "vert" a l'onglet ajouté
            self.InitAspectOnglet()
            for bouton in self.listbtn:
                if bouton.objectName() == onglet:
                    bouton.setStyleSheet("background-color: #2ab51a ; font-weight: bold")

            self.update_scroll_width()

    # suppr de l'onglet par suppression de l'onglet du xml puis rechargement par methode run()
    def suppr_onglet(self, onglet):
        # TODO suppr_onglet
        if self.onglet_actif is None:
            QMessageBox.warning(None,"Avertissement", "Pas d'onglet actif")
            return
        reponse = QMessageBox.warning(None, "Attention",
                                      f"Voulez vous vraiment supprimer l'onglet <br><b>{onglet}<\b><\br> ?",
                                      QMessageBox.Yes | QMessageBox.No)
        if reponse == QMessageBox.No:
            return
        # suppression de l'onglet dans le xml
        tree = ET.parse(PATH_VUES)
        root = tree.getroot()
        for vue in root.findall('vue'):
            if vue.get('id') == onglet:
                root.remove(vue)
        # reecriture du xml avec la nouvelle liste des onglets
        tree.write(PATH_VUES, encoding="utf-8", xml_declaration=True)
        # il faut supprimer le repertoire des symboles correspondant
        rep = os.path.join(PATH_REP,"symbologie",onglet)
        try:
            shutil.rmtree(rep)
        except FileNotFoundError:
            pass
        self.suppr_onglet_perso_from_statusbar()
        self.list_onglet = self.get_onglet_from_XML()
        self.add_onglet_from_xml()
        self.addwidgetQGIS(self.list_widgets_qgis, LIST_VUES_QGIS_A_GARDER)
        self.InitAspectOnglet()
        self.onglet_actif = None

        self.update_scroll_width()

    def deplace_onglet(self,sens):
        # si des vues ne sont pas definis
        if not os.path.isfile(PATH_VUES):
            return
        # AUTRE APPROCHE
        # on reorganise le xml en déplaçant l'ordre des vues
        tree = ET.parse(PATH_VUES)
        root = tree.getroot()
        index = 0
        for vue in root.findall('vue'):
            if vue.get('id') == self.onglet_actif:
                root.remove(vue)
                if sens == "DROITE":
                    root.insert(index + 1,vue)
                elif sens == "GAUCHE":
                    root.insert(index - 1, vue)
            index +=1
        tree.write(PATH_VUES, encoding="utf-8", xml_declaration=True)

        self.suppr_onglet_perso_from_statusbar()
        self.list_onglet = self.get_onglet_from_XML()

        self.add_onglet_from_xml()
        self.addwidgetQGIS(self.list_widgets_qgis, LIST_VUES_QGIS_A_GARDER)
        self.InitAspectOnglet()

        # mettre le style "vert" a l'onglet ajouté
        for bouton in self.listbtn:
            if bouton.objectName() == self.onglet_actif:
                bouton.setStyleSheet("background-color: #2ab51a ; font-weight: bold")

    def modifie_vue(self):
        # TODO modifie_vue
        if self.onglet_actif is None:
            QMessageBox.warning(None, "Attention",
                                      f"Il faut activer un onglet pour le modifier")
            return

        reponse = QMessageBox.warning(None, "Attention",
                                      f"Voulez vous vraiment appliquer la nouvelle vue à l'onglet <br><b>{self.onglet_actif}<\b><\br> ?",
                                      QMessageBox.Yes | QMessageBox.No)
        if reponse == QMessageBox.No:
            return

        if reponse == QMessageBox.Yes:
            list_layer_visible = self.setlist_layer_visible()
            tree = ET.parse(PATH_VUES)
            root = tree.getroot()
            # suppression de tous les layers correspondant à la vue
            self.suppr_all_layer_visible_xml(root, self.onglet_actif)
            # ajout des nouveaux layers correspondant à l'onglet
            self.add_layer_visible_xml(root, self.onglet_actif, list_layer_visible)

            # sauvegarde des styles de tous les layers ajoutés
            self.sauve_style_layer_visible()
            # Sauvegarder les modifications dans le fichier XML
            tree.write(PATH_VUES, encoding='utf-8', xml_declaration=True)

    # retourne la liste des layers visible dans qgis
    def setlist_layer_visible(self):
        layers = QgsProject.instance().mapLayers().values()
        list_layer_visible = []
        for layer in layers:
            if QgsProject.instance().layerTreeRoot().findLayer(layer.id()).isVisible():
                list_layer_visible.append(layer.name())
        return list_layer_visible

    # supprimes les entrées des layers dans le xml correspondant à l'onglet choisi → xml
    def suppr_all_layer_visible_xml(self,root,onglet):
        onglet_tmp = f".//vue[@id='{onglet}']"
        for vue in root.findall(onglet_tmp):
            # Supprimer toutes les balises <layer> sous l'onglet defini
            for layer in vue.findall('layer'):
                vue.remove(layer)

    # ajoute les layer visibles dans l'onglet choisi → xml
    def add_layer_visible_xml(self,root,onglet,list_layer_visible):
        onglet_tmp = root.find(f".//vue[@id='{onglet}']")
        # Ajouter les layers à l'onglet
        for layer in list_layer_visible:
            layer_element = ET.SubElement(onglet_tmp, 'layer')
            layer_element.text = layer
        ET.indent(root, "    ")

    # creation du repertoire et sauvegarde des layers visibles dans le repertoire "symbologie
    # en fonction de l'onglet actif
    def sauve_style_layer_visible(self):
        # TODO sauve_style_layer_visible
        rep = f"{PATH_REP}\symbologie\\{self.onglet_actif}"
        list_layer_visible = self.setlist_layer_visible()
        # Je supprime le repertoire avant de le recréer,
        # ça permet de supprimer les styles directement.
        # Indispensable en cas de modif (style existant que je dois suppr avant de récrire).
        try:
            shutil.rmtree(rep)
        except FileNotFoundError:
            pass
        os.mkdir(rep)
        for layer in list_layer_visible:
            path = f"{PATH_REP}\symbologie\\{self.onglet_actif}\\{layer}.qml"
            layer_tmp = self.getlayer(layer)
            layer_tmp.saveNamedStyle(path,categories=QgsMapLayer.StyleCategory.Symbology| QgsMapLayer.Labeling)
            layer_tmp.triggerRepaint()

    def add_onglet_in_xml(self, onglet):
        # recuperation des layer visible de qgis
        list_layer_visible = self.setlist_layer_visible()
        self.onglet_actif = onglet
        tree = ET.parse(PATH_VUES)
        root = tree.getroot()

        for v in root.findall('vue'):
            if v.get('id') == onglet:
                QMessageBox.warning(None,"Attention",f"L'onglet : <br><b>{self.onglet_actif}</b></br> existe déjà.")
                return

        # Créer une nouvelle vue avec l'ID spécifié
        nouvelle_vue = ET.SubElement(root, 'vue', id=onglet)
        ET.indent(root, "    ")
        # Ajouter les layers à la nouvelle vue
        for layer in list_layer_visible:
            layer_element = ET.SubElement(nouvelle_vue, 'layer')
            layer_element.text = layer
        ET.indent(root, "    ")

        # sauvegarde des styles de tous les layers ajoutés
        self.sauve_style_layer_visible()

        # Sauvegarder les modifications dans le fichier XML
        tree.write(PATH_VUES, encoding='utf-8', xml_declaration=True)

    def add_onglet_from_xml(self):
        for onglet in self.list_onglet:
            btn = QPushButton(onglet)
            btn.setFixedHeight(HAUTEUR_BTN)

            btn.setObjectName(onglet)
            btn.setToolTip(btn.objectName())
            self.listbtn.append(btn)

            metrics = QFontMetrics(btn.font())
            text_width = metrics.horizontalAdvance(btn.objectName())

            btn.setMaximumWidth(text_width+30)
            btn.setSizePolicy(QSizePolicy.MinimumExpanding, QSizePolicy.Fixed)  # largeur minimale selon le texte
            btn.adjustSize()

            self.hlayout_vues.addWidget(btn)

            # gestion clic droit
            btn.installEventFilter(self.filter_clic_droit)

            self.update_scroll_width()

            # "_", ignore le parametre de remplacement pour le premier arguement de : clicked
            btn.clicked.connect(lambda _, bouton=btn: self.changestyle(bouton))

    # renvoi le layer specifié en fonction du nom
    def getlayer(self,nom):
        project = QgsProject.instance()
        layer = project.mapLayersByName(nom)
        if not layer:
            return False
        return layer[0]

    def set_activeLayer(self,nom):
        project = QgsProject.instance()
        layer = project.mapLayersByName(nom)
        if not layer:
            return False
        else:
            self.iface.setActiveLayer(layer[0])
            self.layer = self.iface.activeLayer()
            return True

    # initialise tous les onglets en ecriture noir
    def InitAspectOnglet(self):
        for btn in self.listbtn:
            btn.setStyleSheet("color: black ; font-weight: bold")

    # suppr des onglets perso
    def suppr_onglet_perso_from_statusbar(self):
        for btn in self.listbtn:
            try:
                self.hlayout_vues.removeWidget(btn)
                # retirer le bouton du widget parent
                btn.setParent(None)
            except RuntimeError:
                pass
        self.listbtn.clear()

    def suppr_bouton_defaut(self):
        widgets = self.status_bar.children()
        for widget in widgets:
            try:
                if widget.objectName() in self.list_bouton_defaut:
                    try:
                        self.status_bar.removeWidget(widget)
                        # widget.deleteLater()
                    except TypeError:
                        pass
            except RuntimeError:
                pass

    def init_bouton_defaut(self):
        self.btn_plus = QPushButton(self.icon_plus, None)
        self.btn_moins = QPushButton(self.icon_moins, None)
        self.btn_droit = QPushButton(self.icon_fleche_droite, None)
        self.btn_gauche = QPushButton(self.icon_fleche_gauche, None)
        self.btn_modifie = QPushButton(self.icon_modfie, None)
        self.btn_plus.setObjectName("plus")
        self.btn_moins.setObjectName("moins")
        self.btn_droit.setObjectName("droite")
        self.btn_gauche.setObjectName("gauche")
        self.btn_modifie.setObjectName("modifie")
        self.btn_plus.setFixedHeight(HAUTEUR_BTN)
        self.btn_moins.setFixedHeight(HAUTEUR_BTN)
        self.btn_droit.setFixedHeight(HAUTEUR_BTN)
        self.btn_gauche.setFixedHeight(HAUTEUR_BTN)
        self.btn_modifie.setFixedHeight(HAUTEUR_BTN)

        self.list_bouton_defaut = [self.btn_plus,self.btn_moins,self.btn_gauche,self.btn_droit,self.btn_modifie]

        self.btn_plus.clicked.connect(self.ajout_onglet)
        self.btn_plus.setToolTip("Ajouter un onglet")
        self.btn_moins.clicked.connect(lambda :self.suppr_onglet(self.onglet_actif))
        self.btn_moins.setToolTip("Supprimer un onglet")
        self.btn_modifie.clicked.connect(self.modifie_vue)
        self.btn_modifie.setToolTip("Modifier la symbologie de l'onglet actif")
        self.btn_droit.clicked.connect(lambda _, sens="DROITE": self.deplace_onglet(sens))
        self.btn_droit.setToolTip("Déplacer l'onglet actif vers la droite")
        self.btn_gauche.clicked.connect(lambda _, sens="GAUCHE": self.deplace_onglet(sens))
        self.btn_gauche.setToolTip("Déplacer l'onglet actif vers la gauche")
        self.list_nom_btn_defaut = [self.btn_plus.objectName(), self.btn_moins.objectName(), self.btn_droit.objectName(),
                           self.btn_gauche.objectName(), self.btn_modifie.objectName()]
        return self.list_nom_btn_defaut

    def add_bouton_defaut(self):
        for compt, btn in enumerate(self.list_bouton_defaut):
            # self.status_bar.insertWidget(compt, btn)
            # btn.setObjectName(str(compt))
            self.hlayout_defaut.addWidget(btn)

    def getwidgetsQGIS(self):
        list_widgets = []
        widgets = self.status_bar.children()

        for widget in widgets:
            if type(widget) == QWidget and type(widget) != QHBoxLayout:
                children = widget.children()
                for child in children:
                    if type(child) != QHBoxLayout:
                        try:
                            list_widgets.append(child)
                        except TypeError:
                            pass
        return list_widgets

    def addwidgetQGIS(self,list_widgets_qgis,list_widgets):
        # ajout d'une barre de separation
        self.status_bar.addWidget(self.line)

        for widg in list_widgets_qgis:
            if widg.objectName() not in list_widgets:
                try:
                    widg.hide()
                except AttributeError:
                    pass
            else:
                self.status_bar.addWidget(widg)

    def suppr_widget_qgis(self,list_widgets_qgis):
        for widg in list_widgets_qgis:
            try:
                self.status_bar.removeWidget(widg)
            except TypeError:
                pass

    def suppr_all_widget(self):
        widgets = self.status_bar.children()
        for widg in widgets:
            try:
                self.status_bar.removeWidget(widg)
            except TypeError:
                pass

    def init_arborescence(self):
        retour = False
        if not os.path.exists(PATH_REP):
            os.mkdir(PATH_REP)
            os.mkdir(PATH_REP_VUES)
            os.mkdir(PATH_REP_SYMBOLOGIE)
            os.mkdir(os.path.join(PATH_REP_SYMBOLOGIE,VUE_DEFAUT))
            retour = True
        if not os.path.isfile(PATH_VUES):
            with open(PATH_VUES, "w", encoding="utf-8") as f:
                # initialisation de la structure du xml
                root = ET.Element("vues")
                tree = ET.ElementTree(root)
                tree.write(PATH_VUES, encoding="utf-8", xml_declaration=True)
            retour = True
        return retour

    def update_scroll_width(self):
        # Largeur cumulée des boutons + spacing du layout
        total_width = sum(btn.width() for btn in self.listbtn) + (self.hlayout_vues.spacing() * (
                    len(self.listbtn) - 1)) + self.hlayout_vues.contentsMargins().left() + self.hlayout_vues.contentsMargins().right()
        self.container_vues.setFixedWidth(total_width)
        self.scroll.setMinimumWidth(min(total_width, 800))

    def run(self):
        # pas de couches chargées
        if self.first_start:
            self.first_start = False

            projet = QgsProject.instance()
            if len(projet.mapLayers()) <= 0:
                QMessageBox.warning(None,"Avertissement","Aucun projet chargé")
                return

            # --- Ajouter le ScrollArea dans la status bar ---
            self.status_bar.addWidget(self.container_defaut)
            self.status_bar.addWidget(self.scroll)

            if len(QgsProject.instance().mapLayers()) <= 0:
                return

            # si le dossier ONGLET existe et s'il contient des vues (vues.xml).
            first = self.init_arborescence()

            self.list_onglet = self.get_onglet_from_XML()
            self.suppr_onglet_perso_from_statusbar()
            self.suppr_bouton_defaut()
            self.add_bouton_defaut()
            self.add_onglet_from_xml()
            self.InitAspectOnglet()
            self.add_bouton_defaut()
            if first:
                self.add_onglet_in_xml(VUE_DEFAUT)

            self.addwidgetQGIS(self.list_widgets_qgis, LIST_VUES_QGIS_A_GARDER)

            self.changestyle(self.listbtn[0])
