# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Vue
                                 A QGIS plugin
 gestion des vues
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2024-11-20
        git sha              : $Format:%H$
        copyright            : (C) 2024 by Gérôme PECHEUR
        email                : gerome.pecheur@ign.fr
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from PyQt5.QtCore import  QTimer
from PyQt5.QtGui import QFontMetrics
from PyQt5.QtWidgets import QPushButton, QMessageBox, QHBoxLayout, QWidget, QFrame, QScrollArea, QSizePolicy, \
    QFileDialog, QMenu

from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QInputDialog

from qgis.core import QgsProject,QgsMapLayer


from .dlg_import import *
from copy import copy
import xml.etree.ElementTree as ET
import os
import shutil


class Vue:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):

        # index du bouton actif dans le layout (pour sauvegarder la position dans le fichier pos.txt)
        self.index = None
        self.rep_vues = None
        self.path_xml = None
        # self.filter_clic_droit = ClicDroit(self)

        self.iface = iface
        self.layer = self.iface.activeLayer()

        self.status_bar = self.iface.mainWindow().statusBar()
        self.status_bar.setContentsMargins(0, 0, 0, 0)
        self.status_bar.setFixedHeight(35)

        self.list_bouton_defaut = []
        self.btn_modifie = None
        self.btn_gauche = None
        self.btn_droit = None
        # self.btn_moins = None
        self.btn_plus = None
        self.btn_importer = None

        self.first_start = True

        # self.pos_dernier_onglet = None
        self.list_vues = []

        # --- ScrollArea horizontal ---
        self.scroll = QScrollArea()
        self.scroll.setFixedHeight(30)  # hauteur visible dans la status bar
        self.scroll.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.scroll.setHorizontalScrollBarPolicy(Qt.ScrollBarAsNeeded)
        self.scroll.setWidgetResizable(True)
        self.scroll.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Fixed)
        self.scroll.setStyleSheet("""
            QScrollArea {
                border: none;             
                background: transparent;
            }
            QScrollBar:horizontal {
                background: #f0f0f0;         
                height: 8px
            }
            QScrollBar::handle:horizontal {
                background: #777777;             
            }
        """)

        # Widget interne qui contient le layout des boutons vues
        self.container_vues = QWidget()
        self.container_vues.setSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        self.container_vues.setObjectName("container_vues")

        # Widget interne qui contient le layout des boutons par defaut (+ ,droite ,....)
        self.container_defaut = QWidget()
        self.container_defaut.setSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        # self.container_defaut.setStyleSheet("border: 1px solid blue")
        self.container_defaut.setObjectName("container_defaut")
        # self.container.setAttribute(Qt.WA_StyledBackground, True)

        # --- Layout horizontal (qui contient les boutons des vues) ---
        self.hlayout_vues = QHBoxLayout(self.container_vues)
        self.hlayout_vues.setContentsMargins(0, 3, 0, 0)
        self.hlayout_vues.setSpacing(0)

        # --- Layout horizontal (qui contient les boutons par defaut) ---
        self.hlayout_defaut = QHBoxLayout(self.container_defaut)
        self.hlayout_defaut.setContentsMargins(0, 0, 0, 0)
        self.hlayout_defaut.setSpacing(1)

        # --- Définir le widget interne du ScrollArea ---
        self.scroll.setWidget(self.container_vues)

        self.line = QFrame()
        self.line.setFrameShape(QFrame.VLine)
        self.line.setLineWidth(2)

        self.onglet_actif = None
        self.listbtn = []

        self.list_widgets_qgis = self.getwidgetsQGIS()

        # bouton par defaut
        self.icon_plus = QIcon(os.path.join(os.path.dirname(__file__) , "icons","plus.png"))
        # self.icon_moins = QIcon(os.path.join(os.path.dirname(__file__) , "icons","moins.png"))
        self.icon_fleche_droite = QIcon(os.path.join(os.path.dirname(__file__) , "icons","fleche_droite.png"))
        self.icon_fleche_gauche = QIcon(os.path.join(os.path.dirname(__file__) , "icons","fleche_gauche.png"))
        self.icon_modfie = QIcon(os.path.join(os.path.dirname(__file__) , "icons","modifie.png"))
        self.icon_importer = QIcon(os.path.join(os.path.dirname(__file__), "icons", "importer.png"))

        self.list_nom_btn_defaut = self.init_bouton_defaut()

        # aucun projet chargé
        if not QgsProject.instance().fileName():
            return

    def run_at_startup(self):
        QTimer.singleShot(500, self.run)



    def initGui(self):
        QgsProject.instance().readProject.connect(self.run_at_startup)

    def unload(self):
        self.clear_statusbar_plugin_widgets()

    def clear_statusbar_plugin_widgets(self):
        # Supprime container_defaut
        try:
            self.status_bar.removeWidget(self.container_defaut)
        except Exception:
            pass
        # Supprime scroll
        try:
            self.status_bar.removeWidget(self.scroll)
        except Exception:
            pass
        # Supprime éventuellement la ligne de séparation
        try:
            self.status_bar.removeWidget(self.line)
        except Exception:
            pass

    def on_changestyle(self, bouton):
        # recuperation de la position de l'ongelt actif dans le layout
        # pour sauvegarder la position dans le fichier pos.txt
        self.index = self.hlayout_vues.indexOf(bouton)


        # sauvegarde de l'onglet actif pour gerer la suppression
        self.onglet_actif = bouton.objectName()
        list_layer = self.get_layer_actif_in_vue(bouton.objectName())


        self.InitAspectOnglet()
        # bouton en vert
        bouton.setStyleSheet("background-color: #2ab51a ; font-weight: bold")

        self.masquerlayer(["ALL"])
        self.afficherlayer(list_layer)

        for layer in list_layer:
            layer_tmp = self.getlayer(layer)
            try:
                path_qml = os.path.join(self.rep_vues, bouton.objectName(), f"{layer}.qml")
                layer_tmp.loadNamedStyle(path_qml,categories=QgsMapLayer.StyleCategory.Symbology| QgsMapLayer.Labeling)

                layer_tmp.triggerRepaint()
            # pas de style pour le layer specifié (ou repertoire manquant)
            except AttributeError:
                pass

    def get_dossier_vues(self) -> str:
        """
            Retourne le chemin du dossier des listes.
            :return: str
            """
        project = QgsProject.instance()
        chemin_projet = project.fileName()
        dossier_projet = os.path.dirname(chemin_projet)
        dossier_vues = os.path.join(dossier_projet, REP_VUES)
        return dossier_vues

    # retourne la liste des layers actifs par vues spécifiques
    def get_layer_actif_in_vue(self, vue_active):
        list_layer = []
        rep = os.path.join(self.rep_vues, vue_active)
        for file in os.listdir(rep):
            chemin = os.path.join(rep, file)
            if os.path.isfile(chemin):
                if os.path.splitext(file)[1] == ".qml":
                    list_layer.append(os.path.splitext(file)[0])
        # if len(list_layer) == 0:
        #     QMessageBox.warning(None,"Avertissement",f"Aucun layer n'est associé à la vue : <br><b>{vue_active}</b></br>")
        return list_layer

    # retourne la liste de toutes les vues
    def get_name_all_vues(self):
        # lecture à partir du xml pour récupérer l'ordre d'affichage des vues
        tree = ET.parse(os.path.join(self.rep_vues, XML_VUES))
        root = tree.getroot()
        list_onglet = []
        for vue in root.findall("vue"):
            list_onglet.append(vue.get('id'))
        return list_onglet

    # masque les layer en fonction de l'onglet
    def masquerlayer(self,listlayer):
        list_tmp = []
        if listlayer[0] == "ALL":
            layers = QgsProject.instance().mapLayers()
            for layer_id, layername in layers.items():
                list_tmp.append(layername.name())
            listlayer = copy(list_tmp)
        for layer in listlayer:
            layer_tmp = self.getlayer(layer)
            try:
                QgsProject.instance().layerTreeRoot().findLayer(layer_tmp.id()).setItemVisibilityChecked(False)
            except AttributeError:
                pass


    # rend visible les layers (listlayer)
    def afficherlayer(self,listlayer):
        list_tmp = []
        if len(listlayer) ==0:
            return
        if listlayer[0] == "ALL":
            layers = QgsProject.instance().mapLayers()
            for layer_id,layername in layers.items():
                list_tmp.append(layername.name())
            listlayer = copy(list_tmp)

        for layer in listlayer:
            layer_tmp = self.getlayer(layer)
            if layer_tmp:
                try:
                    QgsProject.instance().layerTreeRoot().findLayer(layer_tmp.id()).setItemVisibilityChecked(True)
                except AttributeError:
                    pass

    # ajout OU modifie un onglet
    def on_ajout_onglet(self):
        # TODO ajout_onglet
        onglet,ok = QInputDialog.getText(None, 'Gestion des vues', 'Veuillez donner un nom à l\'onglet:')
        if ok:
            if not self.add_onglet_in_xml(onglet):
                QMessageBox.warning(None, "Attention", f"L'onglet : <br><b>{self.onglet_actif}</b></br> existe déjà.")
                return
            self.sauve_style_layer_visible()
            self.suppr_onglet_perso_from_statusbar()
            self.list_vues = self.get_name_all_vues()
            self.add_btn_all_vues()
            self.addwidgetQGIS(self.list_widgets_qgis, LIST_VUES_QGIS_A_GARDER)

            # mettre le style "vert" a l'onglet ajouté
            self.InitAspectOnglet()
            for bouton in self.listbtn:
                if bouton.objectName() == onglet:
                    bouton.setStyleSheet("background-color: #2ab51a ; font-weight: bold")

            self.update_scroll_width()

    # suppr de l'onglet par suppression de l'onglet du xml puis rechargement par methode run()
    def on_suppr_vue(self, vue):
        if self.onglet_actif is None:
            QMessageBox.warning(None,"Avertissement", "Pas d'onglet actif")
            return
        # reponse = QMessageBox.warning(None, "Attention",
        #                               f"Voulez vous vraiment supprimer l'onglet <br><b>{vue}<\b><\br> ?",
        #                               QMessageBox.Yes | QMessageBox.No)
        # if reponse == QMessageBox.No:
        #     return
        # suppression de l'onglet dans le xml --> juste pour gérer l'ordre d'affichage des vues
        tree = ET.parse(os.path.join(self.rep_vues, XML_VUES))
        root = tree.getroot()
        for vue_xml in root.findall('vue'):
            if vue_xml.get('id') == vue:
                root.remove(vue_xml)
        tree.write(os.path.join(self.rep_vues, XML_VUES), encoding="utf-8", xml_declaration=True)

        # il faut supprimer le repertoire de la vue correspondante
        rep = os.path.join(self.rep_vues, vue)
        try:
            shutil.rmtree(rep)
        except FileNotFoundError:
            pass
        self.suppr_onglet_perso_from_statusbar()
        self.list_vues = self.get_name_all_vues()
        self.add_btn_all_vues()
        self.addwidgetQGIS(self.list_widgets_qgis, LIST_VUES_QGIS_A_GARDER)
        self.InitAspectOnglet()
        self.onglet_actif = None
        self.update_scroll_width()

    def on_deplace_onglet(self, sens):
        # si des vues ne sont pas definis
        if not os.path.isfile(self.path_xml):
                return
        # AUTRE APPROCHE
        # on reorganise le xml en déplaçant l'ordre des vues
        tree = ET.parse(self.path_xml)
        root = tree.getroot()
        index = 0
        for vue in root.findall('vue'):
            if vue.get('id') == self.onglet_actif:
                root.remove(vue)
                if sens == "DROITE":
                    root.insert(index + 1,vue)
                elif sens == "GAUCHE":
                    root.insert(index - 1, vue)
            index +=1
        tree.write(self.path_xml,encoding="utf-8", xml_declaration=True)

        self.suppr_onglet_perso_from_statusbar()
        self.list_vues = self.get_name_all_vues()

        self.add_btn_all_vues()
        self.addwidgetQGIS(self.list_widgets_qgis, LIST_VUES_QGIS_A_GARDER)
        self.InitAspectOnglet()

        # mettre le style "vert" a l'onglet ajouté
        for bouton in self.listbtn:
            if bouton.objectName() == self.onglet_actif:
                bouton.setStyleSheet("background-color: #2ab51a ; font-weight: bold")

    def on_importer_vue(self):
        dialog = QFileDialog()
        dialog.setWindowTitle("Choisir une vue")  # titre
        dialog.setFileMode(QFileDialog.Directory)  # uniquement dossiers
        dialog.setOptions(QFileDialog.ShowDirsOnly | QFileDialog.DontResolveSymlinks)
        dialog.setLabelText(QFileDialog.Accept, "Sélectionner un dossier 'VUES'")  # texte du bouton

        if dialog.exec_():
            rep_vues_absolu = dialog.selectedFiles()
            rep_vues_absolu = [os.path.abspath(p) for p in rep_vues_absolu]
            rep_vues_nom = os.path.basename(rep_vues_absolu[0])

            if rep_vues_nom != REP_VUES:
                QMessageBox.warning(None, "Attention","Veuillez sélectionner un dossier nommé 'VUES'")
                return

            rep_enfants_absolu = []
            for rep_vue in os.listdir(rep_vues_absolu[0]):
                if os.path.isdir(os.path.join(rep_vues_absolu[0], rep_vue)):
                    rep_enfants_absolu.append(os.path.join(rep_vues_absolu[0],rep_vue))

            dlg_importer = DialogImport()
            dlg_importer.ini_list_view(rep_enfants_absolu)
            if dlg_importer.exec_() == QDialog.Accepted:

                for vue in dlg_importer.vues_a_importer:
                    source = str(os.path.join(rep_vues_absolu[0], vue))
                    dest = str(os.path.join(self.rep_vues, vue))
                    try:
                        # copie des dossiers vue sélectionnés dans le repertoire VUES du projet
                        shutil.copytree(source, dest)
                        # mise à jour du xml et rechargement des vues
                        self.add_onglet_in_xml(vue)
                    except FileExistsError:
                        # QMessageBox.warning(None, "Attention", f"La vue '{os.path.basename(vue)}' existe déjà")
                        res = QMessageBox.question(
                            None,
                            "Mise à jour de la vue",
                            f"La vue <b><span style='color:red;'>{vue}</span></b> existe déjà.\nVoulez-vous la mettre à jour ?",
                            QMessageBox.StandardButton.Yes | QMessageBox.StandardButton.No,
                            QMessageBox.StandardButton.No
                        )
                        if res == QMessageBox.StandardButton.Yes:
                            # suppression avant copie pour mettre à jour la vue
                            shutil.rmtree(dest)
                            shutil.copytree(source, dest)

                            # pas besoin de mettre à jour le xml puisque la vue existe déjà,
                            # on veut écraser la vue existante sans changer son nom
                            # self.add_onglet_in_xml(vue)



                self.suppr_onglet_perso_from_statusbar()
                self.list_vues = self.get_name_all_vues()
                self.add_btn_all_vues()
                self.addwidgetQGIS(self.list_widgets_qgis, LIST_VUES_QGIS_A_GARDER)
                self.InitAspectOnglet()

    def on_modifie_vue(self):
        if self.onglet_actif is None:
            QMessageBox.warning(None, "Attention",
                                      f"Il faut activer un onglet pour le modifier")
            return

        reponse = QMessageBox.warning(None, "Attention",
                                      f"Voulez vous vraiment appliquer la nouvelle vue à l'onglet <br><b>{self.onglet_actif}<\b><\br> ?",
                                      QMessageBox.Yes | QMessageBox.No)
        if reponse == QMessageBox.No:
            return

        if reponse == QMessageBox.Yes:
            # sauvegarde des styles de tous les layers ajoutés
            self.sauve_style_layer_visible()

    def on_show_menu_vue(self,pos, bouton):
        menu = QMenu()
        renommer = menu.addAction("Renommer")
        supprimer = menu.addAction("Supprimer")
        action = menu.exec_(bouton.mapToGlobal(pos))

        if action == renommer:
            self.renomme(bouton)

        if action == supprimer:
            self.onglet_actif = bouton.objectName()
            self.on_suppr_vue(self.onglet_actif)


    # retourne la liste des layers visible dans qgis
    def setlist_layer_visible(self):
        layers = QgsProject.instance().mapLayers().values()
        list_layer_visible = []
        for layer in layers:
            if QgsProject.instance().layerTreeRoot().findLayer(layer.id()).isVisible():
                list_layer_visible.append(layer.name())
        return list_layer_visible

    # creation du repertoire et sauvegarde des layers visibles dans le repertoire "symbologie
    # en fonction de l'onglet actif
    def sauve_style_layer_visible(self):
        # TODO sauve_style_layer_visible
        rep = os.path.join(self.rep_vues, self.onglet_actif)
        list_layer_visible = self.setlist_layer_visible()
        # Je supprime le repertoire avant de le recréer,
        # ça permet de supprimer les styles directement.
        # Indispensable en cas de modif (style existant que je dois suppr avant de récrire).
        try:
            shutil.rmtree(rep)
        except FileNotFoundError:
            pass
        os.mkdir(rep)
        for layer in list_layer_visible:
            path = os.path.join(self.rep_vues, self.onglet_actif, f"{layer}.qml")
            layer_tmp = self.getlayer(layer)
            layer_tmp.saveNamedStyle(path,categories=QgsMapLayer.StyleCategory.Symbology| QgsMapLayer.Labeling)
            layer_tmp.triggerRepaint()

    def add_onglet_in_xml(self, onglet):
        # recuperation des layer visible de qgis
        xml_path = os.path.join(self.rep_vues, XML_VUES)
        self.onglet_actif = onglet
        tree = ET.parse(xml_path)
        root = tree.getroot()

        for v in root.findall('vue'):
            if v.get('id') == onglet:
                QMessageBox.warning(None,"Attention",f"L'onglet : <br><b>{self.onglet_actif}</b></br> existe déjà.")
                return False

        # Créer une nouvelle vue avec l'ID spécifié
        ET.SubElement(root, 'vue', id=onglet)
        ET.indent(tree)  # retour à la ligne

        tree.write(xml_path,encoding='utf-8', xml_declaration=True)
        return True


    def renomme(self, obj):
        dialinput = QInputDialog()
        new_name, ok = dialinput.getText(None, "Modifier le nom", "Nouveau nom :",text = f"{obj.objectName()}")
        if not ok:
            return
        if new_name == "":
            QMessageBox.warning(None,"Erreur","Le nom ne doit pas être vide")
            return
        if "*" in new_name:
            QMessageBox.warning(None, "Erreur", "Le nom ne doit pas être contenir '*'")
            return

        # 1: renommer l'onglet dans le xml
        tree = ET.parse(os.path.join(self.rep_vues, XML_VUES))
        root = tree.getroot()
        for vue in root.findall("vue"):
            if vue.get("id") == obj.objectName():
                vue.set("id", new_name)  # modifier l'attribut 'id'
        tree.write(os.path.join(self.rep_vues, XML_VUES),
                   encoding="utf-8", xml_declaration=True)
        # 2: renommer le dossier correspondant
        os.rename(os.path.join(self.rep_vues, obj.objectName()),
                  os.path.join(self.rep_vues, new_name))

        self.suppr_onglet_perso_from_statusbar()
        self.list_vues = self.get_name_all_vues()
        self.add_btn_all_vues()
        self.InitAspectOnglet()

        self.update_scroll_width()

        # 3 : remettre le btn de la vue active en vert
        for bouton in self.listbtn:
            if new_name == bouton.objectName():
                bouton.setStyleSheet("background-color: #2ab51a ; font-weight: bold")


    def add_btn_all_vues(self):
        for onglet in self.list_vues:
            btn = QPushButton(onglet)
            btn.setFixedHeight(HAUTEUR_BTN)

            btn.setContextMenuPolicy(Qt.CustomContextMenu)
            btn.customContextMenuRequested.connect(lambda pos, b=btn: self.on_show_menu_vue(pos, b))
            # gestion clic droit → remplacé par le menu contextuel
            # btn.installEventFilter(self.filter_clic_droit)

            btn.setObjectName(onglet)
            btn.setToolTip(btn.objectName())
            self.listbtn.append(btn)

            metrics = QFontMetrics(btn.font())
            text_width = metrics.horizontalAdvance(btn.objectName())
            btn.setMaximumWidth(text_width+30)
            btn.setSizePolicy(QSizePolicy.MinimumExpanding, QSizePolicy.Fixed)  # largeur minimale selon le texte
            btn.adjustSize()

            self.hlayout_vues.addWidget(btn)
            self.update_scroll_width()

            # "_", ignore le parametre de remplacement pour le premier arguement de : clicked
            btn.clicked.connect(lambda _, bouton=btn: self.on_changestyle(bouton))

    # renvoi le layer specifié en fonction du nom
    def getlayer(self,nom):
        project = QgsProject.instance()
        layer = project.mapLayersByName(nom)
        if not layer:
            return False
        return layer[0]

    # initialise tous les onglets en écriture noire
    def InitAspectOnglet(self):
        for btn in self.listbtn:
            btn.setStyleSheet("color: black ; font-weight: bold")

    # suppr des onglets perso
    def suppr_onglet_perso_from_statusbar(self):
        for btn in self.listbtn:
            try:
                self.hlayout_vues.removeWidget(btn)
                # retirer le bouton du widget parent
                btn.setParent(None)
            except RuntimeError:
                pass
        self.listbtn.clear()

    def suppr_bouton_defaut(self):
        widgets = self.status_bar.children()
        for widget in widgets:
            try:
                if widget.objectName() in self.list_bouton_defaut:
                    try:
                        self.status_bar.removeWidget(widget)
                        # widget.deleteLater()
                    except TypeError:
                        pass
            except RuntimeError:
                pass

    def init_bouton_defaut(self):
        self.btn_plus = QPushButton(self.icon_plus, None)
        # self.btn_moins = QPushButton(self.icon_moins, None)
        self.btn_droit = QPushButton(self.icon_fleche_droite, None)
        self.btn_gauche = QPushButton(self.icon_fleche_gauche, None)
        self.btn_modifie = QPushButton(self.icon_modfie, None)
        self.btn_importer = QPushButton(self.icon_importer, None)
        self.btn_plus.setObjectName("plus")
        # self.btn_moins.setObjectName("moins")
        self.btn_droit.setObjectName("droite")
        self.btn_gauche.setObjectName("gauche")
        self.btn_modifie.setObjectName("modifie")
        self.btn_importer.setObjectName("importer")
        self.btn_plus.setFixedHeight(HAUTEUR_BTN)
        # self.btn_moins.setFixedHeight(HAUTEUR_BTN)
        self.btn_droit.setFixedHeight(HAUTEUR_BTN)
        self.btn_gauche.setFixedHeight(HAUTEUR_BTN)
        self.btn_modifie.setFixedHeight(HAUTEUR_BTN)
        self.btn_importer.setFixedHeight(HAUTEUR_BTN)

        self.list_bouton_defaut = [self.btn_plus,
                                   # self.btn_moins,
                                   self.btn_gauche,self.btn_droit,self.btn_modifie,self.btn_importer]

        self.btn_plus.clicked.connect(self.on_ajout_onglet)
        self.btn_plus.setToolTip("Ajouter un onglet")
        # self.btn_moins.clicked.connect(lambda :self.on_suppr_vue(self.onglet_actif))
        # self.btn_moins.setToolTip("Supprimer un onglet")
        self.btn_modifie.clicked.connect(self.on_modifie_vue)
        self.btn_modifie.setToolTip("Modifier la symbologie de l'onglet actif")
        self.btn_droit.clicked.connect(lambda _, sens="DROITE": self.on_deplace_onglet(sens))
        self.btn_droit.setToolTip("Déplacer l'onglet actif vers la droite")
        self.btn_gauche.clicked.connect(lambda _, sens="GAUCHE": self.on_deplace_onglet(sens))
        self.btn_gauche.setToolTip("Déplacer l'onglet actif vers la gauche")
        self.btn_importer.clicked.connect(self.on_importer_vue)
        self.btn_importer.setToolTip("Importer une vue")

        self.list_nom_btn_defaut = [self.btn_plus.objectName(),
                                    # self.btn_moins.objectName(),
                                    self.btn_droit.objectName(),
                           self.btn_gauche.objectName(), self.btn_modifie.objectName(),self.btn_importer.objectName()]
        return self.list_nom_btn_defaut

    def add_bouton_defaut(self):
        for compt, btn in enumerate(self.list_bouton_defaut):
            self.hlayout_defaut.addWidget(btn)

    def getwidgetsQGIS(self):
        list_widgets = []
        widgets = self.status_bar.children()

        for widget in widgets:
            if isinstance(widget, QWidget) and type(widget) != QHBoxLayout:
                children = widget.children()
                for child in children:
                    if type(child) != QHBoxLayout:
                        try:
                            list_widgets.append(child)
                        except TypeError:
                            pass
        return list_widgets

    def addwidgetQGIS(self,list_widgets_qgis,list_widgets):
        # ajout d'une barre de separation
        self.status_bar.addWidget(self.line)
        for widg in list_widgets_qgis:
            if isinstance(widg, QWidget):
                if widg.objectName() not in list_widgets:
                    try:
                        widg.hide()
                    except AttributeError:
                        pass
                else:
                    self.status_bar.addWidget(widg)
            else:
                return

    def init_arborescence(self):
        retour = False
        if not os.path.exists(self.rep_vues):
            os.mkdir(self.rep_vues)
            os.mkdir(os.path.join(self.rep_vues, VUE_DEFAUT))
            with open(os.path.join(self.rep_vues, FIC_POS), "w") as f:
                f.write("0")  # position de l'onglet actif (0 par defaut)
            retour = True
        if not os.path.isfile(os.path.join(self.rep_vues, XML_VUES)):
            with open(os.path.join(self.rep_vues, XML_VUES), "w", encoding="utf-8") as f:
                # initialisation de la structure du xml
                root = ET.Element("vues")
                tree = ET.ElementTree(root)
                tree.write(os.path.join(self.rep_vues, XML_VUES),
                           encoding="utf-8", xml_declaration=True)
                retour = True
        return retour

    def update_scroll_width(self):
        # Largeur cumulée des boutons + spacing du layout
        total_width = sum(btn.width() for btn in self.listbtn) + (self.hlayout_vues.spacing() * (
                    len(self.listbtn) - 1)) + self.hlayout_vues.contentsMargins().left() + self.hlayout_vues.contentsMargins().right()
        self.container_vues.setFixedWidth(total_width)
        self.scroll.setMinimumWidth(min(total_width, 800))

    def on_sauve_position(self):
        with open(os.path.join(self.rep_vues, FIC_POS), "w") as f:
            f.write(str(self.index))

    def run(self):
        # pas de couches chargées
        if self.first_start:
            self.first_start = False

            projet = QgsProject.instance()
            if len(projet.mapLayers()) <= 0:
                QMessageBox.warning(None,"Avertissement","Aucun projet chargé")
                return

            self.rep_vues = self.get_dossier_vues()
            self.path_xml = os.path.join(self.rep_vues, XML_VUES)

            # --- Ajouter le ScrollArea dans la status bar ---
            self.status_bar.addWidget(self.container_defaut)
            self.status_bar.addWidget(self.scroll)

            if len(QgsProject.instance().mapLayers()) <= 0:
                return

            # si le dossier ONGLET existe et s'il contient des vues (vues.xml).
            first = self.init_arborescence()
            if first:
                self.add_onglet_in_xml(VUE_DEFAUT)
                self.sauve_style_layer_visible()

            self.list_vues = self.get_name_all_vues()
            self.suppr_onglet_perso_from_statusbar()
            self.suppr_bouton_defaut()
            self.add_bouton_defaut()
            self.add_btn_all_vues()
            self.InitAspectOnglet()

            self.addwidgetQGIS(self.list_widgets_qgis, LIST_VUES_QGIS_A_GARDER)

            # slot
            QgsProject.instance().projectSaved.connect(self.on_sauve_position)

            if self.listbtn:
                pos = 0
                path_fic_pos = os.path.join(self.rep_vues, FIC_POS)
                # lecture de la position de l'onglet actif dans le fichier pos.txt
                if os.path.isfile(path_fic_pos):
                    with open(os.path.join(self.rep_vues, FIC_POS), "r") as f:
                        pos = f.read()
                else:
                    with open(path_fic_pos, "w") as f:
                        f.write("0")  # position de l'onglet actif (0 par defaut)
                self.on_changestyle(self.listbtn[int(pos)])

